// Typed access to src/data/bench.json (generated by scripts/extract-data.mjs from the plugin repo's bench/).
import raw from './data/bench.json';

export interface Side { total: number; inputEq: number; requests: number; toolCalls: number; firstContext: number; quality: number; output: number }
export interface Task {
  id: string; group: 'scratch' | 'existing' | 'academic'; label: string; short: string; title: string; category: string; language: string;
  runs: { native: number; tokenforge: number }; native: Side; tokenforge: Side;
  savings: number; savingsPriceWeighted: number; qualityDiff: number;
}
export interface Series { run: string; lean: string | null; total: number; requests: number; points: number[]; sum: number }
export interface BenchData {
  generated: string; source: string; model: string[]; apiModels: Record<string, number>; runsWithOtherModels: number; contaminatedRuns: number;
  claudeCodeVersion: string; tokenforgeVersion: string; defaultLean: string;
  aggregate: {
    tasks: number; runs: number; medianSavings: number; meanSavings: number; pooledSavings: number; minSavings: number; maxSavings: number;
    medianPriceWeighted: number; medianToolCallReduction: number; minPriceWeighted: number; maxPriceWeighted: number; tasksCheaper: number; tasksCostlier: number; tasksFewerTokens: number; firstRequestOverhead: number;
    scratchMedian: number; existingMedian: number; scratchTasks: number; existingTasks: number; academicTasks: number; academicMedian: number; qualityWorse: string[];
  };
  lean: { level: string; tokens: number }[];
  curve: { task: string; label: string; title: string; series: { native: Series; tokenforge: Series } };
  tasks: Task[];
}

export const data = raw as BenchData;
export const MODEL_NAME = 'Claude Opus 5.5';
